### PR TITLE
Debug simd energy

### PR DESCRIPTION
**Pull request by berenger-eu**
Uncomment the test and see

### CODE REVIEW

**Comment by berenger-eu** [comment]
I fail to reproduce this error :( I will have to investigate why

**Comment by kain88-de** [comment]
I get this on a recent ubuntu build

```
❯ gcc --version
gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Do you have the same compiler? I have not tested clang yet

**Comment by kain88-de** [comment]
so this works without modifications using clang14

**Comment by kain88-de** [comment]
So compiler bugs. Yeah

**Comment by berenger-eu** [comment]
I have g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
I will try with docker and the same compiler

**Comment by berenger-eu** [comment]
So I will not try with docker soon due to time constraints, but I found an intermediate optimized version that seems to pass. If it is OK for you we can merge it.

**Pull request merged**
