### PR TITLE
Make inastemp a submodule

### PR DESCRIPTION
**Pull request by berenger-eu**
Replace the hard files with a submodule (to benefit more easily from the update in inastemp)

- [x]  Remove old files
- [x]  Add submodule
- [x]  Update the doc
- [x]  Update the script
- [x]  Update the CI/Docker

### CODE REVIEW

**Comment by berenger-eu** [comment]
Be aware that it seems not nice to play with git submodule while using the same directory (ext/inastemp) as where the original source files were... But will be ok once merged.

**Comment by berenger-eu** [comment]
We will see if that impact #22 #21

**Comment by kain88-de** [comment]
Do bother updating the docker images. We do not need them for the build. Github actions runs on a ubuntu VM, we can use that as is. Currently we still need to install libyaml-cpp. But I'm good with that.

**Comment by berenger-eu** [comment]
I am also OK with libyaml.

**Comment by berenger-eu** [comment]
[2bb50ec](https://github.com/bio-phys/complexespp/pull/23/commits/2bb50ec82627815beab06c060917487fd6e0ce4a) a minus seems missing. I am not able to look at the history of the file (or to access the old repository) but I have the feeling that it was something we did solve in the past, but I might be wrong. Anyway, now it seems fine (well, the tests will tell us).

**Pull request merged**
