### PR TITLE
Forbid unknow params, register the one accessed with hasKey

### PR DESCRIPTION
**Pull request by berenger-eu**
In my previous branch #30 it was possible to pass a parameter that is invalid (like comples++ SQDFQSD).
It is not the case anymore. I wait for the CI to see if everything is fine, and that would be great if anyone can do a quick test on a PC.

### CODE REVIEW

**Comment by berenger-eu** [comment]
Nope it seems I have some issues

**Comment by berenger-eu** [comment]
Yes we were using "nb-thread=x" without "s", and it was causing an issue because now it is forbidden to pass an argument that is not registered.

**Comment by berenger-eu** [comment]
I was not supported "-c" for configure. or True (in addition to TRUE and true) as boolean.

**Comment by berenger-eu** [comment]
What should I do to have the CI running?
@Clownshift This branch should fix your problem with the command line, but it is unclear if you will still have issues.

**Comment by Clownshift** [comment]
I only did a little testing and generally it seems to work. However, the help message is a little misleading.
I can run a simulations with `complexes++ -c equilibrate.conf`, however, `complexes++ --config equilibrate.conf` leads to a core dump:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  File "" does not exist.

Aborted (core dumped)
```
Btw, simply executing `complexes++` without any other arguments leads to the same issue. 
Can we get a little more verbose messages for these cases?
Besides, when I execute `complexes++ -h` the copyright block isnt being printed, which is somewhat inconsistent with, e.g., `complexes++ --version`, where we print the copyright block and then the output of the version request.

**Comment by berenger-eu** [comment]
Yes, I was having a bug for -c --config, now it should be OK. Also, I now print the copyright directly at the start of the main (so it should be here no matter if the app crashes quickly). I hope it is fine. Does this remove your segfault?

**Comment by kain88-de** [comment]
If running with no arguments we could print the help. That would work too. Especially since we require some arguments.

**Comment by berenger-eu** [comment]
Ok, I updated it, and print something at the beginning of the help if there is no param or that the mandatory params are missing. I am missing some time to test deeply but it seems to work.

**Comment by berenger-eu** [comment]
Ok I play with it and it seems OK. Putting a parameters that does not exist will print the help, not putting version OR help OR config will print the help. And the rest seems fine.

**Pull request merged**
