### PR TITLE
Backup logfile

### PR DESCRIPTION
**Pull request by berenger-eu**
In the solution I did, I use an intermediate buffer.
Once we know if we have to backup the file or not, we do it for the log file, then open the right log file and potentially flush the buffer.
Anyone can change to something else another option seems better.

### CODE REVIEW

**Comment by berenger-eu** [comment]
Related to #6

**Comment by berenger-eu** [comment]
@Clownshift Could you have a look by running simulations and see if the behavior is as expected?
@kain88-de Could you look at the code and modify it if needed? or tell me what to do?
Thanks!

**Comment by Clownshift** [comment]
> @Clownshift Could you have a look by running simulations and see if the behavior is as expected? 

Currently, I cannot compile,  thus I cannot test. 
I think this is related to a bug on the main branch, not to the changes made here. I will wait for a rebase.

**Comment by kain88-de** [comment]
@berenger-eu if this works for you. That is good enough for me. Once tests are running in CI again we can add an app-test for this as well.

**Comment by berenger-eu** [comment]
@Clownshift This should be fine for testing now? Thanks.

**Comment by kain88-de** [comment]
have a try again. CLI parsing should work better now.

**Comment by Clownshift** [comment]
Waiting for a fix for #29 .

**Comment by berenger-eu** [comment]
@Clownshift I hope this time it is OK for testing.

**Comment by berenger-eu** [comment]
I rebase on main after the change on command line manager.

**Comment by Clownshift** [comment]
I rebased this on the current main branch and it looks alright.
However, in generated log file is a little inconsistent with the stdout:
* the seeds (user seed and program seed) are only printed as integer, without specification before and no linebrakes after:
Instead of :
```
[LOG] user seed: 3333
[LOG] program seed: 2454988800
[LOG]
```
we get: `[LOG] [LOG] [LOG] 3333[LOG] 2454988800[LOG] `
* Furthermore, we do not print the Program information and the structure and options section to file. Would it be challenging to have these two blocks in the log file as well?

**Comment by berenger-eu** [comment]
I just rebased.

**Comment by berenger-eu** [comment]
Ok this is weird, here is backup log file that I get, it seems OK.
[backup_2022-03-28:15-26-39_complexes.log](https://github.com/bio-phys/complexespp/files/8363157/backup_2022-03-28.15-26-39_complexes.log)

**Comment by Clownshift** [comment]
> Ok this is weird, here is backup log file that I get, it seems OK. [backup_2022-03-28:15-26-39_complexes.log](https://github.com/bio-phys/complexespp/files/8363157/backup_2022-03-28.15-26-39_complexes.log)

Is it possible, that you created the backed-up file with the old version?
How does the newly written log file look like?

**Comment by Clownshift** [comment]
Because the backup machinery generally works. However, in the course of implementing that the format of the log file changed. 
This is what I meant above.

**Comment by Clownshift** [comment]
I am pretty sure that you  are looking at the backups from old versions, because in this file you can also the the hash of the version with which these simulations have been performed. Also in this file you actually have multiple simulations appended in one file, which does not happen anymore, with the new backup machinery.

But also for that reason, it would be good, if the log files still contain the info about the version and so on, which they currently do not contain anymore...

> Ok this is weird, here is backup log file that I get, it seems OK. [backup_2022-03-28:15-26-39_complexes.log](https://github.com/bio-phys/complexespp/files/8363157/backup_2022-03-28.15-26-39_complexes.log)

**Comment by berenger-eu** [comment]
Yes you are right, what I have now is ugly :)

**Comment by berenger-eu** [comment]
Ok it seems fine now (did not try after I pull).

**Comment by berenger-eu** [comment]
I look forward to see if it can be merged.

**Comment by Clownshift** [comment]
For me it looks good.

**Pull request merged**
