### PR TITLE
Remove the remaining of boost

### PR DESCRIPTION
**Pull request by berenger-eu**
This PR should remove all the parts related to boost.
I updated the CL with MPI.
Also there are some remaining here:
`
./complexes++/test/app-test/soft-core-energy/generate-reference-softcore-potential.ipynb:      "[LOG] compilation libs: /home/max/academia/projects/complexes/complexes++/build/release/ext/xdrfile-1.1.4/1.1.4/lib/libxdrfile.a;/usr/lib/libyaml-cpp.so;/usr/lib/libfmt.a;/usr/lib/libboost_program_options.so;/usr/lib/libboost_system.so;/usr/lib/libboost_filesystem.so\n",
./complexes++/test/app-test/wca-energy/generate-reference-wca-potential.ipynb:      "[LOG] compilation libs: /home/max/academia/projects/complexes/complexes++/build/release/ext/xdrfile-1.1.4/1.1.4/lib/libxdrfile.a;/usr/lib/libyaml-cpp.so;/usr/lib/libfmt.a;/usr/lib/libboost_program_options.so;/usr/lib/libboost_system.so;/usr/lib/libboost_filesystem.so\n",
./complexes++/test/statistic-test/gaussian-domain/Linker distribution testing.ipynb:      "[LOG] compilation libs: /home/max/academia/projects/complexes/complexes++/build/release/ext/xdrfile-1.1.4/1.1.4/lib/libxdrfile.a;/usr/lib/libyaml-cpp.so;/usr/lib/libfmt.a;/usr/lib/libnetcdf_c++4.so;/usr/lib/libnetcdf.so;/usr/lib/libhdf5_hl.so;/usr/lib/libhdf5.so;/usr/lib/libz.so;/usr/lib/libdl.so;/usr/lib/libboost_program_options.so;/usr/lib/libboost_system.so;/usr/lib/libboost_filesystem.so\n",
./complexes++/test/statistic-test/gaussian-domain/Linker distribution testing.ipynb:      "[LOG] compilation libs: /home/max/academia/projects/complexes/complexes++/build/release/ext/xdrfile-1.1.4/1.1.4/lib/libxdrfile.a;/usr/lib/libyaml-cpp.so;/usr/lib/libfmt.a;/usr/lib/libnetcdf_c++4.so;/usr/lib/libnetcdf.so;/usr/lib/libhdf5_hl.so;/usr/lib/libhdf5.so;/usr/lib/libz.so;/usr/lib/libdl.so;/usr/lib/libboost_program_options.so;/usr/lib/libboost_system.so;/usr/lib/libboost_filesystem.so\n",
`

### CODE REVIEW

**Comment by berenger-eu** [comment]
@kain88-de Could you have a look?
I cannot compile complexes for a reason I cannot explain, so I am working blindly...
It seems FMT is causing me a problem (do we remove FMT?).
Thanks.

**Comment by Clownshift** [comment]
> @kain88-de Could you have a look? I cannot compile complexes for a reason I cannot explain, so I am working blindly... It seems FMT is causing me a problem (do we remove FMT?). Thanks.

Same for me.

**Comment by kain88-de** [comment]
Hard to say anything without logs. The CI shows an error with the change. 

Do you have gym installed on the system? Cmake is a bit tricky if the library is also installed on the system.

**Comment by berenger-eu** [comment]
[comp-error.txt](https://github.com/bio-phys/complexespp/files/8305587/comp-error.txt)
is what I get, @Clownshift same as you?
At first it seems I use the "right" fmt (the one installed with the script).

**Comment by Clownshift** [comment]
> [comp-error.txt](https://github.com/bio-phys/complexespp/files/8305587/comp-error.txt) is what I get, @Clownshift same as you? At first it seems I use the "right" fmt (the one installed with the script).

So, I think the error is pretty much the same. I suggest to move the discussion here #26

**Comment by kain88-de** [comment]
Can you remove `$HOME/complexes-pp` and try the build again with *this* branch?

**Comment by kain88-de** [comment]
Good. Yeah the other things still need fixing.

**Pull request merged**
