### PR TITLE
Clean cl names

### PR DESCRIPTION
**Pull request by berenger-eu**
Typos, I was using "_" instead of "-" for the parameters, now should always be "-", like "nb-threads=x".
I now print the errors from the command line.
I now accept --list-param=x y z in addition to --list-param x y z (so with and without =)

### CODE REVIEW

**Comment by Clownshift** [comment]
We do have some specific error messages, now, which is very helpful. And also the names of the arguments are now consistent in terms of `-` vs`_`. Therefore, I suppose #33 is fixed.

**Comment by Clownshift** [comment]
However the behavior of multidir is still strange
The behavior is still strange:
If I execute: `complexes++ --config config --multidir=simulation-temp-298 simulation-temp-318`
I get 
```
[ERROR] The following arguments are invalid:
[ERROR] "simulation-temp-318"
```
If I execute: `complexes++ --config config --multidir simulation-temp-298 simulation-temp-318`
I get: 
```
[ERROR] The following arguments are invalid:
[ERROR] "simulation-temp-298"
[ERROR] "simulation-temp-318"
```
If I execute: `complexes++ --config config --multidir=simulation-temp-298` it works (in a single dir)
If I execute: `complexes++ --config config --multidir simulation-temp-298`, it yields an error:
```
[ERROR] The following arguments are invalid:
[ERROR] "simulation-temp-298"
```
Apparently, it still expects the `=` ...

**Comment by Clownshift** [comment]
I really do not understand, why `complexes++ --config config --multidir simulation-temp-298 simulation-temp-318` 
does not work, though. 
the parser does recognize all arguments, still says, they are "invalid". 

By the way also the wildcard expansion: `complexes++ --config config --multidir simulation-temp-*`
yields a consistent error:
```
[ERROR] The following arguments are invalid:
[ERROR] "simulation-temp-298"
[ERROR] "simulation-temp-318"
[ERROR] "simulation-temp-338"
[ERROR] "simulation-temp-358"
[ERROR] "simulation-temp-378"
[ERROR] "simulation-temp-398"
```

**Comment by berenger-eu** [comment]
Yeap, I had a big bug (and I was not testing with names that were leading to the error), I think it should be better now. (Sorry for that, doing the unit test of the cl tool is on my todo list...)

**Comment by Clownshift** [comment]
Since, I already prepared it, for future reference. Small test case:
https://syncandshare.lrz.de/getlink/fiSxvytKFZaVCzo8bo8FghLP/multidir.tar.gz

**Comment by Clownshift** [comment]
That seems to work, perfectly fine. Fixes #32

**Comment by kain88-de** [comment]
I'm hitting some endless loops now running the tests. Not sure if connected. THe next step should probably be to get the tests running

**Pull request merged**
